SimulationProject.PL/ViewModels/HomeVMs/HomeVM.cs
using SimulationProject.BL.DTOs;

namespace SimulationProject.PL.ViewModels;

public class HomeVM
{
    public SettingsDTO Settings { get; set; }

    public IEnumerable<CardViewItem> Cards { get; set; }
}

SimulationProject.PL/Areas/Admin/Controllers/AccountController.cs
using Microsoft.AspNetCore.Mvc;
using SimulationProject.BL.DTOs;
using SimulationProject.BL.Services.Abstractions;
using SimulationProject.Core.Enums;

namespace SimulationProject.PL.Areas.Admin.Controllers;

[Area("Admin")]
public class AccountController : Controller
{
    readonly IAccountService _accountService;

    public AccountController(IAccountService accountService)
    {
        _accountService = accountService;
    }

    public IActionResult Login()
    {
        if (User.Identity is not null && User.Identity.IsAuthenticated)
        {
            return Redirect(User.IsInRole(Roles.Admin.ToString()) ? "/admin" : "/");
        }

        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Login(AppUserLoginDTO dto, string? returnUrl = null)
    {
        if (!ModelState.IsValid)
        {
            return View(dto);
        }

        try
        {
            await _accountService.LoginAsync(dto);
        }
        catch (Exception)
        {
            ModelState.AddModelError("CustomError", "Something went wrong!");
            return View(dto);
        }
        
        return Redirect(returnUrl ?? (User.IsInRole(Roles.Admin.ToString()) ? "/admin" : "/"));
    }

    public async Task<IActionResult> Logout()
    {
        await _accountService.LogoutAsync();

        return RedirectToAction(nameof(Login));
    }
}

SimulationProject.PL/Areas/Admin/Controllers/CardController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SimulationProject.BL.DTOs;
using SimulationProject.BL.Exceptions;
using SimulationProject.BL.Services.Abstractions;

namespace SimulationProject.PL.Areas.Admin.Controllers;

[Area("Admin")]
[Authorize(Roles = "Admin")]
public class CardController : Controller
{
    readonly ICardService _service;
    readonly IMapper _mapper;

    public CardController(ICardService service, IMapper mapper)
    {
        _service = service;
        _mapper = mapper;
    }

    public async Task<IActionResult> Index(int page = 0, int count = 3)
    {
        IEnumerable<CardListItemDTO> list = await _service.GetAllAsync(page, count);
        ViewData["Page"] = page;
        ViewData["TotalCount"] = _service.Count();

        return View(list);
    }

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(CardCreateDTO dto)
    {
        if (!ModelState.IsValid)
        {
            return View(dto);
        }

        try
        {
            await _service.CreateAsync(dto, User.Identity.Name);
            await _service.SaveChangesAsync();
        }
        catch (TypeMustBeImageException ex)
        {
            ModelState.AddModelError("CustomError", ex.Message);
            return View(dto);
        }
        catch (Exception)
        {
            ModelState.AddModelError("CustomError", "Something went wrong!");
            return View(dto);
        }

        return RedirectToAction(nameof(Index));
    }

    public async Task<IActionResult> Update(int id)
    {
        try
        {
            return View(_mapper.Map<CardUpdateDTO>(await _service.GetByIdAsync(id)));
        }
        catch (Exception)
        {
            return BadRequest();
        }
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Update(CardUpdateDTO dto)
    {
        if (!ModelState.IsValid)
        {
            return View(dto);
        }

        try
        {
            await _service.UpdateAsync(dto, User.Identity.Name);
            await _service.SaveChangesAsync();
        }
        catch (TypeMustBeImageException ex)
        {
            ModelState.AddModelError("CustomError", ex.Message);
            return View(dto);
        }
        catch (Exception)
        {
            ModelState.AddModelError("CustomError", "Something went wrong!");
            return View(dto);
        }

        return RedirectToAction(nameof(Index));
    }

    public async Task<IActionResult> HardDelete(int id)
    {
        try
        {
            await _service.HardDeleteAsync(id);
            await _service.SaveChangesAsync();
        }
        catch (Exception)
        {
            return BadRequest();
        }
        return RedirectToAction(nameof(Index));
    }

    public async Task<IActionResult> SoftDelete(int id)
    {
        try
        {
            await _service.SoftDeleteAsync(id, User.Identity.Name);
            await _service.SaveChangesAsync();
        }
        catch (Exception)
        {
            return BadRequest();
        }
        return RedirectToAction(nameof(Index));
    }

    public async Task<IActionResult> Recover(int id)
    {
        try
        {
            await _service.RecoverAsync(id);
            await _service.SaveChangesAsync();
        }
        catch (Exception)
        {
            return BadRequest();
        }
        return RedirectToAction(nameof(Index));
    }

    public async Task<IActionResult> Details(int id)
    {
        try
        {
            return View(await _service.GetByIdAsync(id));
        }
        catch (Exception)
        {
            return BadRequest();
        }
    }
}

SimulationProject.PL/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace SimulationProject.PL.Areas.Admin.Controllers;

[Area("Admin")]
[Authorize(Roles = "Admin")]
public class DashboardController : Controller
{
    public IActionResult Index()
    {
        return View();
    }
}

SimulationProject.PL/Areas/Admin/Controllers/SettingsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SimulationProject.BL.DTOs;
using SimulationProject.BL.Services.Abstractions;

namespace SimulationProject.PL.Areas.Admin.Controllers;

[Area("Admin")]
[Authorize(Roles = "Admin")]
public class SettingsController : Controller
{
    readonly ISettingService _service;

    public SettingsController(ISettingService service)
    {
        _service = service;
    }

    public async Task<IActionResult> Index()
    {
        return View(await _service.GetSettingsAsync());
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Index(SettingsDTO dto)
    {
        if (!ModelState.IsValid)
        {
            return View(dto);
        }

        try
        {
            _service.UpdateSettings(dto);
            await _service.SaveChangesAsync();
        }
        catch (Exception)
        {
            ModelState.AddModelError("CustomError", "Something went wrong!");
            return View(dto);
        }

        return View(dto);
    }
}

SimulationProject.PL/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SimulationProject.BL.Services.Abstractions;
using SimulationProject.PL.ViewModels;

namespace SimulationProject.PL.Controllers;

public class HomeController : Controller
{
    readonly ISettingService _settingService;
    readonly ICardService _cardService;

    public HomeController(ISettingService settingService, ICardService cardService)
    {
        _settingService = settingService;
        _cardService = cardService;
    }

    public async Task<IActionResult> Index()
    {
        HomeVM VM = new()
        {
            Settings = await _settingService.GetSettingsAsync(),
            Cards = await _cardService.GetAllActiveAsync()
        };

        return View(VM);
    }
}

SimulationProject.PL/Areas/Admin/Views/Card/Create.cshtml
@model CardCreateDTO

<form asp-action="Create" class="container" method="POST" enctype="multipart/form-data">
    <h2 class="my-4">Create Card</h2>
    <div class="mb-3">
        <label class="form-label" asp-for="@Model.Title"></label>
        <input class="form-control" asp-for="@Model.Title" />
        <span class="text-danger" asp-validation-for="@Model.Title"></span>
    </div>
    <div class="mb-3">
        <label class="form-label" asp-for="@Model.Description"></label>
        <input class="form-control" asp-for="@Model.Description" />
        <span class="text-danger" asp-validation-for="@Model.Description"></span>
    </div>
    <div class="mb-3">
        <label class="form-label" asp-for="@Model.Image"></label>
        <input class="form-control" asp-for="@Model.Image" />
        <span class="text-danger" asp-validation-for="@Model.Image"></span>
    </div>
    <p class="text-danger text-center">@Html.ValidationMessage("CustomError")</p>

    <button type="submit" class="btn btn-primary">Save Changes</button>
</form>

SimulationProject.PL/Areas/Admin/Views/Card/Details.cshtml
@model Card

<div class="container">
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Card Details</h6>
        </div>
        <div class="card-body">
            <p>Id: @Model.Id</p>
            <p>Title: @Model.Title</p>
            <p>Description: @Model.Description</p>
            <p>Image: <img style="height: 150px;" src="~/uploads/cards/@Model.ImagePath" /></p>
            <p>Created by: @Model.CreatedBy</p>
            <p>Create time: @Model.CreatedAt</p>
            @if (Model.UpdatedBy is not null)
            {
                <p>Updated by: @Model.UpdatedBy</p>
            }
            @if (Model.UpdatedAt is not null)
            {
                <p>Update time: @Model.UpdatedAt</p>
            }
            @if (Model.DeletedBy is not null)
            {
                <p>Deleted by: @Model.DeletedBy</p>
            }
            @if (Model.DeletedAt is not null)
            {
                <p>Delete time: @Model.DeletedAt</p>
            }
            <p>Deleted: @Model.IsDeleted</p>
        </div>
    </div>
</div>

SimulationProject.PL/Areas/Admin/Views/Card/Index.cshtml
@model IEnumerable<CardListItemDTO>
@{
    int currentPage = ViewData["Page"] is not null ? Convert.ToInt32(ViewData["Page"]) : 0;
    double totalCount = ViewData["TotalCount"] is not null ? Convert.ToDouble(ViewData["TotalCount"]) : 0.00;
    int pageCount = (int) Math.Ceiling(totalCount / 3);
}

<!-- Begin Page Content -->
<div class="container-fluid">
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Cards</h6>
        </div>
        <div class="d-flex justify-content-end px-3">
            <a class="btn btn-primary mt-3" style="width: 160px" asp-controller="Card" asp-action="Create">+ Add Card</a>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Title</th>
                            <th>Deleted</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (CardListItemDTO item in Model)
                        {
                            <tr>
                                <td>@item.Id</td>
                                <td>@item.Title</td>
                                <td>@item.IsDeleted</td>
                                <td>
                                    <a class="btn btn-primary" asp-controller="Card" asp-action="Update" asp-route-id="@item.Id">Update</a>
                                    @if (item.IsDeleted)
                                    {
                                        <a class="btn btn-success" asp-controller="Card" asp-action="Recover" asp-route-id="@item.Id">Recover</a>
                                    } else {
                                        <a class="btn btn-danger" asp-controller="Card" asp-action="SoftDelete" asp-route-id="@item.Id">Soft Delete</a>
                                    }
                                    <a class="btn btn-danger" asp-controller="Card" asp-action="HardDelete" asp-route-id="@item.Id">Hard Delete</a>
                                    <a class="btn btn-info" asp-controller="Card" asp-action="Details" asp-route-id="@item.Id">Details</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>

                <div class="col-sm-12 col-md-7">
                    <div class="dataTables_paginate paging_simple_numbers">
                        <ul class="pagination">
                            @if (currentPage - 1 >= 0)
                            {
                                <li class="paginate_button page-item previous"><a asp-route-page="@(currentPage - 1)" tabindex="0" class="page-link">Previous</a></li>
                            }
                            @if (pageCount > 1)
                            {
                                for (int i = 0; i < pageCount; i++)
                                {
                                    <li class="paginate_button page-item @(currentPage == i ? "active" : "")"><a asp-route-page="@i" tabindex="0" class="page-link">@(i + 1)</a></li>
                                }
                            }
                            @if (pageCount > currentPage + 1)
                            {
                                <li class="paginate_button page-item next"><a asp-route-page="@(currentPage + 1)" tabindex="0" class="page-link">Next</a></li>
                            }
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /.container-fluid -->
<!-- Page level plugins -->
<script src="~/admin/vendor/datatables/jquery.dataTables.min.js" defer></script>
<script src="~/admin/vendor/datatables/dataTables.bootstrap4.min.js" defer></script>

<!-- Page level custom scripts -->
<script src="~/admin/js/demo/datatables-demo.js" defer></script>

SimulationProject.PL/Areas/Admin/Views/Card/Update.cshtml
@model CardUpdateDTO

<form asp-action="Update" class="container" method="POST" enctype="multipart/form-data">
    <h2 class="my-4">Update Card</h2>
    <input type="hidden" asp-for="@Model.Id" />
    <div class="mb-3">
        <label class="form-label" asp-for="@Model.Title"></label>
        <input class="form-control" asp-for="@Model.Title" />
        <span class="text-danger" asp-validation-for="@Model.Title"></span>
    </div>
    <div class="mb-3">
        <label class="form-label" asp-for="@Model.Description"></label>
        <input class="form-control" asp-for="@Model.Description" />
        <span class="text-danger" asp-validation-for="@Model.Description"></span>
    </div>
    <div class="mb-3">
        <label class="form-label" asp-for="@Model.Image"></label>
        <input class="form-control" asp-for="@Model.Image" />
        <img style="height: 150px;" src="~/uploads/cards/@Model.ImagePath" />
        <span class="text-danger" asp-validation-for="@Model.Image"></span>
    </div>
    <p class="text-danger text-center">@Html.ValidationMessage("CustomError")</p>

    <button type="submit" class="btn btn-primary">Save Changes</button>
</form>

SimulationProject.PL/Areas/Admin/Views/Settings/Index.cshtml
@model SettingsDTO

<form asp-action="Index" class="container" method="POST">
    <h2 class="my-4">Settings</h2>
    <div class="mb-3">
        <input class="form-control" asp-for="Address" />
        <span class="text-danger" asp-validation-for="Address"></span>
    </div>
    <div class="mb-3">
        <input class="form-control" asp-for="Email" />
        <span class="text-danger" asp-validation-for="Email"></span>
    </div>
    <div class="mb-3">
        <input class="form-control" asp-for="PhoneNumber" />
        <span class="text-danger" asp-validation-for="PhoneNumber"></span>
    </div>
    <div class="mb-3">
        <input class="form-control" asp-for="TwitterURL" />
        <span class="text-danger" asp-validation-for="TwitterURL"></span>
    </div>
    <div class="mb-3">
        <input class="form-control" asp-for="FacebookURL" />
        <span class="text-danger" asp-validation-for="FacebookURL"></span>
    </div>
    <div class="mb-3">
        <input class="form-control" asp-for="InstagramURL" />
        <span class="text-danger" asp-validation-for="InstagramURL"></span>
    </div>
    <div class="mb-3">
        <input class="form-control" asp-for="LinkedinURL" />
        <span class="text-danger" asp-validation-for="LinkedinURL"></span>
    </div>
    <p class="text-danger text-center">@Html.ValidationMessage("CustomError")</p>

    <button type="submit" class="btn btn-primary">Save Changes</button>
</form>

SimulationProject.PL/Views/Home/Index.cshtml
@model HomeVM

<!-- ======= Hero Section ======= -->
<section id="hero">
    <div class="hero-container">
        <h1>Welcome to Siimple</h1>
        <h2>Please, fill out the for below to be notified for the latest updates!</h2>

        <form action="forms/notify.php" method="post" role="form" class="php-email-form">
            <div class="row no-gutters">
                <div class="col-md-6 form-group pr-md-1">
                    <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" required>
                </div>
                <div class="col-md-6 form-group pl-md-1">
                    <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" required>
                </div>
            </div>

            <div class="my-3">
                <div class="loading">Loading</div>
                <div class="error-message"></div>
                <div class="sent-message">Your notification request was sent. Thank you!</div>
            </div>
            <div class="text-center"><button type="submit">Notify me!</button></div>
        </form>
    </div>
</section><!-- #hero -->

<main id="main">

    <!-- ======= About Section ======= -->
    <section id="about" class="about">
        <div class="container">

            <div class="row">
                <div class="col-lg-6">
                    <img src="~/assets/img/about-img.jpg" class="img-fluid" alt="">
                </div>
                <div class="col-lg-6 pt-4 pt-lg-0">
                    <h3>Voluptatem dignissimos provident quasi corporis voluptates sit assumenda.</h3>
                    <p class="fst-italic">
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
                        magna aliqua.
                    </p>
                    <ul>
                        <li><i class="bx bx-check-double"></i> Ullamco laboris nisi ut aliquip ex ea commodo consequat.</li>
                        <li><i class="bx bx-check-double"></i> Duis aute irure dolor in reprehenderit in voluptate velit.</li>
                        <li><i class="bx bx-check-double"></i> Ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate trideta storacalaperda mastiro dolore eu fugiat nulla pariatur.</li>
                    </ul>
                    <p>
                        Ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
                        velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
                        culpa qui officia deserunt mollit anim id est laborum
                    </p>
                </div>
            </div>

        </div>
    </section>
    <!-- End About Section -->

    @if (Model.Cards is not null)
    {
        <!-- ======= Why Us Section ======= -->
        <section id="why-us" class="why-us section-bg">
            <div class="container">
                <div class="row">
                    @foreach (CardViewItem card in Model.Cards)
                    {
                        <div class="col-lg-4 col-md-6 d-flex align-items-stretch">
                            <div class="card">
                                <img src="~/uploads/cards/@card.ImagePath" class="card-img-top" alt="@card.Title">
                                <div class="card-icon">
                                    <i class="bx bx-book-reader"></i>
                                </div>
                                <div class="card-body">
                                    <h5 class="card-title"><a href="">@card.Title</a></h5>
                                    <p class="card-text">@card.Description</p>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </section>
        <!-- End Why Us Section -->
    }

    <!-- ======= Frequenty Asked Questions Section ======= -->
    <section class="faq">
        <div class="container">

            <div class="section-title">
                <h2>Frequenty Asked Questions</h2>
            </div>

            <ul class="faq-list">

                <li>
                    <a data-bs-toggle="collapse" class="collapsed" data-bs-target="#faq1">Non consectetur a erat nam at lectus urna duis? <i class="bx bx-down-arrow-alt icon-show"></i><i class="bx bx-x icon-close"></i></a>
                    <div id="faq1" class="collapse" data-bs-parent=".faq-list">
                        <p>
                            Feugiat pretium nibh ipsum consequat. Tempus iaculis urna id volutpat lacus laoreet non curabitur gravida. Venenatis lectus magna fringilla urna porttitor rhoncus dolor purus non.
                        </p>
                    </div>
                </li>

                <li>
                    <a data-bs-toggle="collapse" data-bs-target="#faq2" class="collapsed">Feugiat scelerisque varius morbi enim nunc faucibus a pellentesque? <i class="bx bx-down-arrow-alt icon-show"></i><i class="bx bx-x icon-close"></i></a>
                    <div id="faq2" class="collapse" data-bs-parent=".faq-list">
                        <p>
                            Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi. Id interdum velit laoreet id donec ultrices. Fringilla phasellus faucibus scelerisque eleifend donec pretium. Est pellentesque elit ullamcorper dignissim. Mauris ultrices eros in cursus turpis massa tincidunt dui.
                        </p>
                    </div>
                </li>

                <li>
                    <a data-bs-toggle="collapse" data-bs-target="#faq3" class="collapsed">Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi? <i class="bx bx-down-arrow-alt icon-show"></i><i class="bx bx-x icon-close"></i></a>
                    <div id="faq3" class="collapse" data-bs-parent=".faq-list">
                        <p>
                            Eleifend mi in nulla posuere sollicitudin aliquam ultrices sagittis orci. Faucibus pulvinar elementum integer enim. Sem nulla pharetra diam sit amet nisl suscipit. Rutrum tellus pellentesque eu tincidunt. Lectus urna duis convallis convallis tellus. Urna molestie at elementum eu facilisis sed odio morbi quis
                        </p>
                    </div>
                </li>

                <li>
                    <a data-bs-toggle="collapse" data-bs-target="#faq4" class="collapsed">Ac odio tempor orci dapibus. Aliquam eleifend mi in nulla? <i class="bx bx-down-arrow-alt icon-show"></i><i class="bx bx-x icon-close"></i></a>
                    <div id="faq4" class="collapse" data-bs-parent=".faq-list">
                        <p>
                            Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi. Id interdum velit laoreet id donec ultrices. Fringilla phasellus faucibus scelerisque eleifend donec pretium. Est pellentesque elit ullamcorper dignissim. Mauris ultrices eros in cursus turpis massa tincidunt dui.
                        </p>
                    </div>
                </li>

                <li>
                    <a data-bs-toggle="collapse" data-bs-target="#faq5" class="collapsed">Tempus quam pellentesque nec nam aliquam sem et tortor consequat? <i class="bx bx-down-arrow-alt icon-show"></i><i class="bx bx-x icon-close"></i></a>
                    <div id="faq5" class="collapse" data-bs-parent=".faq-list">
                        <p>
                            Molestie a iaculis at erat pellentesque adipiscing commodo. Dignissim suspendisse in est ante in. Nunc vel risus commodo viverra maecenas accumsan. Sit amet nisl suscipit adipiscing bibendum est. Purus gravida quis blandit turpis cursus in
                        </p>
                    </div>
                </li>

                <li>
                    <a data-bs-toggle="collapse" data-bs-target="#faq6" class="collapsed">Tortor vitae purus faucibus ornare. Varius vel pharetra vel turpis nunc eget lorem dolor? <i class="bx bx-down-arrow-alt icon-show"></i><i class="bx bx-x icon-close"></i></a>
                    <div id="faq6" class="collapse" data-bs-parent=".faq-list">
                        <p>
                            Laoreet sit amet cursus sit amet dictum sit amet justo. Mauris vitae ultricies leo integer malesuada nunc vel. Tincidunt eget nullam non nisi est sit amet. Turpis nunc eget lorem dolor sed. Ut venenatis tellus in metus vulputate eu scelerisque. Pellentesque diam volutpat commodo sed egestas egestas fringilla phasellus faucibus. Nibh tellus molestie nunc non blandit massa enim nec.
                        </p>
                    </div>
                </li>

            </ul>

        </div>
    </section><!-- End Frequenty Asked Questions Section -->
    <!-- ======= Contact Us Section ======= -->
    <section id="contact" class="contact section-bg">
        <div class="container">

            <div class="section-title">
                <h2>Contact Us</h2>
            </div>

            <div class="row justify-content-center">

                <div class="col-lg-3 col-md-5 mb-5 mb-md-0">
                    <div class="info">
                        @if (Model.Settings.Address is not null && Model.Settings.Address != "")
                        {
                            <div class="address">
                                <i class="bx bx-map"></i>
                                <p>@Model.Settings.Address</p>
                            </div>
                        }
                        
                        @if (Model.Settings.Email is not null && Model.Settings.Email != "")
                        {
                            <div class="email">
                                <i class="bx bx-envelope"></i>
                                <p>@Model.Settings.Email</p>
                            </div>
                        }
                        
                        @if (Model.Settings.PhoneNumber is not null && Model.Settings.PhoneNumber != "")
                        {
                            <div class="phone">
                                <i class="bx bx-phone-call"></i>
                                <p>@Model.Settings.PhoneNumber</p>
                            </div>
                        }

                        
                    </div>

                    <div class="social-links">
                        @if (Model.Settings.TwitterURL is not null && Model.Settings.TwitterURL != "")
                        {
                            <a href="@Model.Settings.TwitterURL" class="twitter"><i class="bx bxl-twitter"></i></a>
                        }
                        @if (Model.Settings.FacebookURL is not null && Model.Settings.FacebookURL != "")
                        {
                            <a href="@Model.Settings.FacebookURL" class="facebook"><i class="bx bxl-facebook"></i></a>
                        }
                        @if (Model.Settings.InstagramURL is not null && Model.Settings.InstagramURL != "")
                        {
                            <a href="@Model.Settings.InstagramURL" class="instagram"><i class="bx bxl-instagram"></i></a>
                        }
                        @if (Model.Settings.LinkedinURL is not null && Model.Settings.LinkedinURL != "")
                        {
                            <a href="@Model.Settings.LinkedinURL" class="linkedin"><i class="bx bxl-linkedin"></i></a>
                        }
                    </div>

                </div>

                <div class="col-lg-5 col-md-7">
                    <form action="forms/contact.php" method="post" role="form" class="php-email-form">
                        <div class="form-group">
                            <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" required>
                        </div>
                        <div class="form-group mt-3">
                            <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" required>
                        </div>
                        <div class="form-group mt-3">
                            <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" required>
                        </div>
                        <div class="form-group mt-3">
                            <textarea class="form-control" name="message" rows="5" placeholder="Message" required></textarea>
                        </div>
                        <div class="my-3">
                            <div class="loading">Loading</div>
                            <div class="error-message"></div>
                            <div class="sent-message">Your message has been sent. Thank you!</div>
                        </div>
                        <div class="text-center"><button type="submit">Send Message</button></div>
                    </form>
                </div>

            </div>

        </div>
    </section><!-- End Contact Us Section -->

</main><!-- End #main -->